version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
max_jobs: 1
clone_folder: C:\projects\YEngine
test: off

os: Visual Studio 2015
platform: x64

before_build:
  - 7z x wxWidgets.7z -aos -oC:\projects\deps\wxWidgets > null
  
build_script:
 - cd C:\projects\YEngine\apps\theMachine\build
 - cmake .. -G "Visual Studio 14 Win64"
 - msbuild Application.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
 
install:
  # Create directory to store dependencies
  - mkdir C:\projects\deps
  - cd C:\projects\deps
  # Install CMake
  - set CMAKE_URL="https://cmake.org/files/v3.7/cmake-3.7.2-win64-x64.zip"
  - appveyor DownloadFile %CMAKE_URL% -FileName cmake.zip
  - 7z x cmake.zip -oC:\projects\deps > nul
  - move C:\projects\deps\cmake-* C:\projects\deps\cmake # Move to a version-agnostic directory
  - set PATH=C:\projects\deps\cmake\bin;%PATH%
  - cmake --version
  # Install wxwidget
  - appveyor DownloadFile "https://dl.dropboxusercontent.com/s/c1by0uulee6g8th/wxWidgets.7z?dl=0" -FileName wxWidgets.7z
  - set WXWIN=C:\projects\deps\wxWidgets
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;C:\projects\deps\wxWidgets;%PATH%
  - set COMMIT_SHA=%APPVEYOR_REPO_COMMIT:~0,8%
  
build:
  project:
  parallel: true
  verbosity: detailed
  
notifications:
  - provider: Email
    to:
      - yoan.audureau@gmail.com
      #- webery84@gmail.com
      
    subject: 'Build {{status}}'                 
    message: "<div style="font-family:'Segoe UI',Arial,Sans-Serif;font-size:10pt;">
    {{#passed}}
    <h1 style="font-size: 150%;font-weight:normal; color:#078DC7;"><a href="{{buildUrl}}" style="color:#078DC7;">Build {{projectName}} {{buildVersion}} completed</a></h1>{{/passed}}
    {{#failed}}
    <h1 style="font-size: 150%;font-weight:normal; color:#ff3228;"><a href="{{buildUrl}}" style="color:#ff3228;">Build {{projectName}} {{buildVersion}} failed</a></h1>{{/failed}}
    <p style="color: #888;">
        Commit <a href="{{commitUrl}}">{{commitId}}</a> by <a href="mailto:{{commitAuthorEmail}}">{{commitAuthor}}</a> on {{commitDate}}:
        <br />
        <span style="font-size: 110%;color:#222;">{{commitMessage}}</span>
    </p>
    <p><a href="{{notificationSettingsUrl}}" style="font-size:85%;color:#999;">Configure your notification preferences</a></p>
</div>"    # optional
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
