version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
max_jobs: 1
clone_folder: C:\projects\YEngine
test: off

os: Visual Studio 2015
platform: x64
  
build_script:
 - cd C:\projects\YEngine\
 - mkdir build
 - cd build\
 - cmake .. -G "Visual Studio 14 Win64"
 - msbuild YEngine.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
 
install:
  # Create directory to store dependencies
  - mkdir C:\projects\deps
  - cd C:\projects\deps
  # Install CMake
  - set CMAKE_URL="https://cmake.org/files/v3.7/cmake-3.7.2-win64-x64.zip"
  - appveyor DownloadFile %CMAKE_URL% -FileName cmake.zip
  - 7z x cmake.zip -oC:\projects\deps > nul
  - move C:\projects\deps\cmake-* C:\projects\deps\cmake # Move to a version-agnostic directory
  - set PATH=C:\projects\deps\cmake\bin;%PATH%
  - cmake --version
  
build:
  project:
  parallel: true
  verbosity: detailed
  
notifications:
  - provider: Email
    to:
      - yoan.audureau@gmail.com
      - webery84@gmail.com
    #subject: 'Build {{status}}'                 
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
